### ISSUE TITLE
Default presets

### ISSUE THREAD

**Issue by maxlk96** [minsulander/vatiris#16]
To encourage/suggest a standard view for new users. 

Possible to auto generate some presets from ICAO and position type (TWR APP etc) 

Window size %of screen instead of predefined px position

**Comment by minsulander** [comment]
Implemented functionality for default presets with different layouts for different screen sizes. Using JSON files in the repo, imported in frontend. For now. This probably needs to change to some backend storage in the future. A `preset.makeDefault()` function can be used from the browser console so that you can set it up like you want, and then copy-paste the function return value into a JSON file. It's a start.

Now we just need to come up with some good defaults and routines for maintaining them...  🤷
